{% set name = "barfi" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/barfi-{{ version }}.tar.gz
  sha256: bed8da8d82dcf553ac20eff51e48df25e002160a486275122e32a3884ba6f5bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - streamlit >=0.63
    - networkx >=2.6.2

test:
  imports:
    - barfi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/krish-adi/barfi
  summary: Framework for a graphical programming environment.
  dev_url: https://github.com/krish-adi/barfi
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
